UHPPOTED-SSMP-MIB DEFINITIONS ::= BEGIN

IMPORTS
    MODULE-IDENTITY, OBJECT-TYPE, enterprises, Integer32
        FROM SNMPv2-SMI
    MODULE-COMPLIANCE, OBJECT-GROUP
        FROM SNMPv2-CONF;

uhppotedSSMP MODULE-IDENTITY
    LAST-UPDATED "202407290000Z"
    ORGANIZATION "github.com/uhppoted"
    CONTACT-INFO    
        "email: uhppoted.development@gmail.com"
    DESCRIPTION
        "MIB objects for the uhppoted breakout board"
    REVISION "202407290000Z"
        DESCRIPTION "First draft"
    ::= { enterprises 65536 }

internal   OBJECT IDENTIFIER ::= { uhppotedSSMP 0 }
system     OBJECT IDENTIFIER ::= { uhppotedSSMP 1 }
controller OBJECT IDENTIFIER ::= { uhppotedSSMP 2 }
events     OBJECT IDENTIFIER ::= { uhppotedSSMP 3 }

-- system
boardId OBJECT-TYPE
    SYNTAX      OCTET STRING (SIZE(0..32))
    MAX-ACCESS  read-only
    STATUS      current
    DESCRIPTION
        "An integer object representing the RP2040 board ID."
    ::= { system 1 }

-- controller
controllerId OBJECT-TYPE
    SYNTAX      Integer32 (0..2147483647)
    MAX-ACCESS  read-only
    STATUS      current
    DESCRIPTION
        "An integer object representing the controller ID."
    ::= { controller 1 }

controllerVersion OBJECT-TYPE
    SYNTAX      OCTET STRING (SIZE(2))
    MAX-ACCESS  read-only
    STATUS      current
    DESCRIPTION
        "A 2 byte octet string representing the controller firmware version (major,minor)."
    ::= { controller 2 }

controllerReleased OBJECT-TYPE
    SYNTAX      OCTET STRING (SIZE(8))
    MAX-ACCESS  read-only
    STATUS      current
    DESCRIPTION
        "An 8 byte octet string representing the controller firmware release date (YYYYMMDD)."
    ::= { controller 3 }

controllerAddress OBJECT-TYPE
    SYNTAX      OCTET STRING (SIZE(4))
    MAX-ACCESS  read-only
    STATUS      current
    DESCRIPTION
        "A 4 byte octet string representing the controller IPv4 address."
    ::= { controller 4 }

controllerNetmask OBJECT-TYPE
    SYNTAX      OCTET STRING (SIZE(4))
    MAX-ACCESS  read-only
    STATUS      current
    DESCRIPTION
        "A 4 byte octet string representing the controller IPv4 netmask."
    ::= { controller 5 }

controllerGateway OBJECT-TYPE
    SYNTAX      OCTET STRING (SIZE(4))
    MAX-ACCESS  read-only
    STATUS      current
    DESCRIPTION
        "A 4 byte octet string representing the controller IPv4 gateway address."
    ::= { controller 6 }

controllerMAC OBJECT-TYPE
    SYNTAX      OCTET STRING (SIZE(6))
    MAX-ACCESS  read-only
    STATUS      current
    DESCRIPTION
        "A 6 byte octet string representing the controller MAC address."
    ::= { controller 7 }

controllerDateTime OBJECT-TYPE
    SYNTAX      OCTET STRING (SIZE(6))
    MAX-ACCESS  read-only
    STATUS      current
    DESCRIPTION
        "A 19 byte octet string representing the controller date/time formatted YYYY-MM-dd HH:mm:ss."
    ::= { controller 8 }

-- events
eventsListenerAddress OBJECT-TYPE
    SYNTAX      OCTET STRING (SIZE(4))
    MAX-ACCESS  read-only
    STATUS      current
    DESCRIPTION
        "A 6 byte octet string representing the controller IPv4 address:port."
    ::= { events 1 }

eventsListenerInterval OBJECT-TYPE
    SYNTAX      Integer8 (0..255)
    MAX-ACCESS  read-only
    MAX-ACCESS  read-only
    STATUS      current
    DESCRIPTION
        "An byte object representing the events auto-send interval (seconds)."
    ::= { events 2 }

-- groups
systemGroup OBJECT-GROUP
    OBJECTS { boardId }
    STATUS  current
    DESCRIPTION
        "System information."
    ::= { internal 1 }

controllerGroup OBJECT-GROUP
    OBJECTS { controllerId, 
              controllerVersion, 
              controllerReleased,
              controllerAddress,
              controllerNetmask,
              controllerGateway,
              controllerMAC,
              controllerDateTime }
    STATUS  current
    DESCRIPTION
        "Controller configuration information."
    ::= { internal 2 }

eventsGroup OBJECT-GROUP
    OBJECTS { eventsListenerAddress, 
              eventsListenerInterval }
    STATUS  current
    DESCRIPTION
        "Event subsystem configuration information."
    ::= { internal 3 }

-- compliance
compliance MODULE-COMPLIANCE
    STATUS  current
    DESCRIPTION
        "The compliance statement for the system and controller groups."
    MODULE  -- this module
    MANDATORY-GROUPS { systemGroup, 
                       controllerGroup 
                       eventsGroup }
    ::= { internal 0 }

END
